### ISSUE TITLE
Native packages for Fedora

### ISSUE THREAD

**Issue by dmirgaleev** [dipdup-io/stone-packaging#15]
Create a workflow to generate Fedora packages of the prover, triggered by a git tag based on commits in the [stone-prover](https://github.com/baking-bad/stone-prover) repository.
https://github.com/dipdup-io/stone-packaging/blob/master/.github/workflows/release.yml and https://github.com/dipdup-io/stone-packaging/blob/master/package_deb.sh can be used as examples.

- Testing should be done in a forked repo and testing results should be provided.
- [README](https://github.com/dipdup-io/stone-packaging?tab=readme-ov-file#download-native-packages-for-debianubuntu) should be extended with instructions similar to.

**Comment by ScottyDavies** [comment]
Hello @dmirgaleev I am open to work on this

**Comment by dmirgaleev** [comment]
Hey @ScottyDavies! Thank you for your interest in the project! To better coordinate the work, please join our Discord server https://discord.gg/aG8XKuwsQd, where you can find the #stone-support channel.

**Comment by ShantelPeters** [comment]
i will love to take this up when the OD hack begins tomorrow @dmirgaleev

**Comment by akintewe** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I have a degree in computer science and have worked extensively with React Native, Flutter, Swift, and Kotlin as a mobile developer. I have familiarity with GitLab CI and GitHub Actions CI/CD workflows. I'm skilled at writing Bash scripts and have experience containerising data using Docker. I have a strong basis in systems programming and package management from my computer science degree, which helps me to comprehend Fedora's packaging system.

### How I plan on tackling this issue
In order to start a new GitHub Actions workflow file, I would fork the stone-prover repository. In my method, I would start with a Fedora base image and use rpmbuild to build the prover. Using the given Debian example as a guide, I would write a bash script to manage the generation of RPM packages. Git tags would start the workflow, which would then compile the prover, create the RPM package, and execute some simple tests. To test the RPM in a clean Fedora environment, I would use mock. Once the installation and functionality of the package have been confirmed, I would update the README with instructions unique to Fedora. Lastly, I would include thorough testing findings and documentation in a pull request.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Hello , i am a frontend and blockchain developer , with a strong background in Next.js, Typescript,Javascript,React,and cario.and i am exicted to contribute my skills to this project . i am avaliable to work . please assign me

### How I plan on tackling this issue
1.I will review the example files: release.yml  and package_deb.sh from the referenced repository to understand their structure.
2.Then i will create a workflow similar to release.yml  but for generating Fedora packages.
3.Also  Modify `package_deb.sh` to fit Fedora package creation requirements.
4.Then i will  Implement git tag-based triggers in your workflow to ensure the package is generated on tagged commits.
5.Next i will  test the workflow in a forked repository.
6. Also provide testing results and ensure the workflow successfully generates Fedora packages.
7.Finally i will  update the README with clear instructions on the Fedora packaging process, similar to the example documentation.

**Comment by bruhhgnik** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Starting to gain experience working with CI/CD pipelines. I have previously worked on ML models usinng python, and i have also worked on smart contract development in eth. I am looking it diversify my portfolio and i dont hesitate in taking up with something new.

### How I plan on tackling this issue
Sstart by analyzing the existing example files in the linked repositories. Then, I would set up a GitHub Actions workflow that triggers on Git tag commits to automate Homebrew package generation. 
I would tehn test this in a forked repository and adjust based on results

**Comment by dmirgaleev** [comment]
Hello @bruhhgnik! Welcome aboard! Please don't hesitate to join our Telegram group [t.me/baking_bad_odhack](https://t.me/baking_bad_odhack) to ask questions and share your progress! Happy hacking!

**Comment by bruhhgnik** [comment]
@dmirgaleev Hey! thanks a lot for this, looking forward to this!
