### ISSUE TITLE
[Book] Generating proof

### ISSUE THREAD

**Issue by dmirgaleev** [dipdup-io/stone-packaging#30]
Add a documentation page describing how to run Stone prover given all the input arguments. It has to also include a section about docker-based setup.

Path to your markdown file: `docs/pages/usage/proving.md`

References:
* https://github.com/starkware-libs/stone-prover?tab=readme-ov-file#creating-and-verifying-a-proof-of-a-cairo-program

**Comment by Calebux** [comment]
I'll like to work on this when OD hack starts

**Comment by martinvibes** [comment]
hello @dmirgaleev i am a blockchain developer and a technical writer
please can i work on this issue :) and would love to be a contributor


here are some of the docs i have writting:
[https://github.com/cairo-book/cairo-book/blob/main/src/ch16-05-01-price-feeds.md](https://github.com/cairo-book/cairo-book/blob/main/src/ch16-05-01-price-feeds.md)
[https://github.com/bandada-infra/bandada/blob/main/README.md](https://github.com/bandada-infra/bandada/blob/main/README.md)
[https://github.com/lfglabs-dev/starknet.quest/blob/testnet/docs/CONTRIBUTING.md](https://github.com/lfglabs-dev/starknet.quest/blob/testnet/docs/CONTRIBUTING.md)

please assign me :)

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
hello i am a frontend developer and a technical writer 
please can i work on this issue :)
i would love to be a contributor on this repo

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
hello @dmirgaleev can I take on this 

### How I plan on tackling this issue
I did love to work on implementing this documentation

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
My name is Benjamin, and I can create a documentation page that explains how to run the Stone prover. I have contributed to 18 projects since joining OnlyDust, and I’m experienced in writing documentation, so I’m excited to tackle this task.

### How I plan on tackling this issue
The goal of this documentation is to provide clear instructions on how to run the Stone prover with all the necessary input arguments. I want to make sure it’s easy for anyone to understand, especially those who might be new to it.

I will also include a section about setting up the Stone prover using Docker. Many users find Docker helpful because it simplifies the installation process, so I want to ensure we cover that.

This information will be organized in a markdown file at docs/pages/usage/proving.md, making it easy for anyone to find.

To gather the necessary details, I will refer to the Stone Prover GitHub Repository. This resource has important information on creating and verifying proofs for Cairo programs, which will be really useful for this documentation.

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
hello i am a frontend developer and a technical writer 
please can i work on this issue :)
i would love to be a contributor on this repo


### How I plan on tackling this issue
please kindly assign me and i'll get straight to work

**Comment by dmirgaleev** [comment]
Hello @martinvibes! Welcome aboard! Please don't hesitate to join our Telegram group https://t.me/baking_bad_odhack to ask questions and share your progress!  Happy hacking!

**Comment by martinvibes** [comment]
@dmirgaleev thank you will get to work

**Comment by Kaminar-i** [comment]
hello @dmirgaleev can i take on this issue

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
hello i am a frontend developer and a technical writer 
please can i work on this issue :)
i would love to be a contributor on this repo

### How I plan on tackling this issue
kindly assign :)

**Comment by dmirgaleev** [comment]
Hello @Kaminar-i! Welcome aboard! Please don't hesitate to join our Telegram group [t.me/baking_bad_odhack](https://t.me/baking_bad_odhack) to ask questions and share your progress! Happy hacking!

**Comment by dmirgaleev** [comment]
Friendly heads up that you have until Sunday (October 6) to push your final PR. @Kaminar-i
