### ISSUE TITLE
[Book] Verifying proof

### ISSUE THREAD

**Issue by dmirgaleev** [dipdup-io/stone-packaging#31]
Add a documentation page describing how to verify Stone proof using the binary. It also has to include a section about docker based setup.

Path to your markdown file: `docs/pages/usage/verifying.md`

References:
* https://github.com/starkware-libs/stone-prover?tab=readme-ov-file#creating-and-verifying-a-proof-of-a-cairo-program

**Comment by Jemiiah** [comment]
I’d love to work on this @d

**Comment by Joy-Adah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Hi. My name is Joy and I am a web3 developer and contributor. I also have experience in writing documentations. 

### How I plan on tackling this issue
I plan to approach this by writing a clear and concise documentation that contains a step by step process describing how to verify stone proof using the binary. I will ensure the documentation also includes setting up with docker.

**Comment by raizo07** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Hello I'll like to be assigned to work on this. 

I'm a software Dev with over four years experience and have worked on a couple of projects here. Here's a link to my profile https://app.onlydust.com/u/raizo07

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
@dmirgaleev I will love to work on this, please assign

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
My name is Benjamin, and I can work on adding a documentation page that explains how to verify Stone proofs using the binary. Since joining OnlyDust, I have made 18 contributions, and I have experience in writing clear documentation, so I’m ready to take on this task.

### How I plan on tackling this issue
The goal of this documentation is to make it easy for users to understand how to verify Stone proofs. I want to break it down in a way that anyone can follow, even if they’re not experts in the topic.

I also plan to include a section about setting up verification using Docker. Many people find Docker helpful because it simplifies the installation process, so I think it’s important to share that information.

This documentation will be written in a markdown file located at `docs/pages/usage/verifying.md`, so it’ll be easy for everyone to access.

To get all the details I need, I’ll refer to the Stone Prover GitHub Repository. This resource has great information about creating and verifying proofs for Cairo programs, which will help a lot in putting together the documentation.

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Hello, I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is an article I wrote for Karst https://medium.com/@josephchimebuka/krast-a-decentralized-social-graph-built-on-starknet-with-erc-6551-c4c9800b5a9d

### How I plan on tackling this issue
I will add a documentation page describing how to verify Stone proof using the binary. And I will conclude in 2-3 days

**Comment by MatiasAchucarro** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I am a passionate and results-driven web developer, currently deepening my knowledge in web3 technologies, Cairo, and open-source development through Dojo Coding. My skill set includes expertise in JavaScript, React, HTML, CSS, C# with .NET Entity Framework, and more. I also have experience with tools like Git, GitHub, SQL Server, and Postman. My focus has been on building solid web applications, from task lists to full-fledged CRUD systems, with front-end, back-end, and database integration.


### How I plan on tackling this issue
To add documentation on verifying the Stone proof and Docker setup in docs/pages/usage/verifying.md, I would take the following steps:

Create or edit the file: Access verifying.md.

Include binary verification: Add brief instructions on how to verify a Stone proof using the binary, based on the provided reference.

Add Docker configuration: Include concise steps for setting up the environment using Docker.

Review: Ensure the instructions are clear and functional.

**Comment by raizo07** [comment]
@dmirgaleev Acknowledged.

**Comment by dmirgaleev** [comment]
Hello @raizo07! Welcome aboard! Please don't hesitate to join our Telegram group https://t.me/baking_bad_odhack to ask questions and share your progress!  Happy hacking!

**Comment by dmirgaleev** [comment]
Hey @raizo07! Do you have any progress so far?

**Comment by raizo07** [comment]
Yes @dmirgaleev I'm just testing now to make sure everything works fine according to the docs, will send an updated pr today

**Comment by dmirgaleev** [comment]
Thanks, it's merged!

**Comment by raizo07** [comment]
> Thanks, it's merged!

You're welcome.
