### ISSUE TITLE
[Book] Examples

### ISSUE THREAD

**Issue by dmirgaleev** [dipdup-io/stone-packaging#32]
Add a documentation page containing a list of reference test files, namely:
* Cairo sources
* Execution artifacts (trace, memory, input, output)
* Prover parameters & config
* Proof

It also has to contain a brief description of what the program does, its arguments (if applicable).

Path to your markdown file: `docs/pages/examples.md`

References:
* https://github.com/dipdup-io/stone-packaging/tree/master/test_files
* https://github.com/starkware-libs/stone-prover?tab=readme-ov-file#creating-and-verifying-a-proof-of-a-cairo-program

**Comment by raizo07** [comment]
Can I work on this

**Comment by martinvibes** [comment]
hello @dmirgaleev please let me work on this :)

**Comment by pheobeayo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I am a web3 frontend developer and Technical writer skilled in Typescript, Javascript, Solidity, Cairo and Rust. I also do lots off documentations on Readme files. This will help me in carrying out this task seamlessly.

### How I plan on tackling this issue
- I will read through the sources files provided and understand the extend of the documentations.
- I will explain what the program does and implement that in the documentation.

**Comment by Osatuyi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Can I be assigned this

### How I plan on tackling this issue
I can do this

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
@dmirgaleev can I work on this please

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I’m Benjamin, and I’m excited to work on adding a new documentation page for our project that will list reference test files. Since joining OnlyDust, I’ve made 18 contributions, and I’m confident in my documentation skills, so I believe I can make this page very useful for our community.

### How I plan on tackling this issue
The goal is to set up a page that lists various test files. 
Here’s what I plan to include:

- Cairo Sources: The actual code for the Cairo programs.
- Execution Artifacts: This will cover traces, memory data, and input/output files to show how the programs run.
- Prover Parameters & Config: Details about the settings used when running the programs.
- Proof: The proof generated from each Cairo program.
I’ll make sure each entry has a simple description explaining what the program does and any arguments it might take. This way, users can quickly get the hang of what each program is about.

I’ll save this new markdown file in the docs/pages/examples.md path to keep everything organized.

To help me gather all the info and examples, 
I’ll check out these resources:

1. DipDup Stone Packaging Test Files: This repository has a bunch of useful test files we can feature.

2. Stone Prover Repository: This one offers great tips on creating and verifying proofs for Cairo programs.

3. Once I put together all the reference test files and fill out the documentation, I’ll review everything to make sure it’s clear and easy to understand. Then, I’ll share it with you for feedback, so we can ensure it really meets the needs of what its meant for.

**Comment by devcollinss** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
My name is Collins Ikechukwu. I'm a full stack blockchain developer developer.amd a technical writer 

### How I plan on tackling this issue
1. **Create a Documentation Page**  
Start by creating a new markdown file at the specified path:  
`docs/pages/examples.md`

2. **List Reference Test Files**  
On the page, list reference test files that include:
   - Cairo sources
   - Execution artifacts (trace, memory, input, output)
   - Prover parameters & config
   - Proof

3. **Brief Program Descriptions**  
For each program, include a brief description that explains:
   - What the program does
   - Any arguments it accepts (if applicable)

4. **Use Existing References**  
Refer to existing test files and examples from:
   - [Test File Examples](https://github.com/dipdup-io/stone-packaging/tree/master/test_files)
   - [Proof Creation](https://github.com/starkware-libs/stone-prover?tab=readme-ov-file#creating-and-verifying-a-proof-of-a-cairo-program)

**Comment by Benjtalkshow** [comment]
@dmirgaleev  Thanks will begin working asap

**Comment by dmirgaleev** [comment]
Hello @Benjtalkshow! Welcome aboard! Please don't hesitate to join our Telegram group https://t.me/baking_bad_odhack to ask questions and share your progress!  Happy hacking!

**Comment by Benjtalkshow** [comment]
> Hello @Benjtalkshow! Welcome aboard! Please don't hesitate to join our Telegram group https://t.me/baking_bad_odhack to ask questions and share your progress! Happy hacking!

Alright. Thanks

**Comment by dmirgaleev** [comment]
Friendly heads up that you have until Sunday (October 6) to push your final PR. @Benjtalkshow

**Comment by Benjtalkshow** [comment]
> Friendly heads up that you have until Sunday (October 6) to push your final PR. @Benjtalkshow

Alright ser

**Comment by Osatuyi** [comment]
Can I be assigned this issue @dmirgaleev

**Comment by ShantelPeters** [comment]
Hi @dmirgaleev  please can I be assigned to this issue.. I am available to work

**Comment by 0xdevcollins** [comment]
Hello @dmirgaleev, may I give this a try?

**Comment by baitcode** [comment]
@dmirgaleev I'd love to contribute here. I understand the structure of test data and happy to document it. I can also improve on example programs (to have arguments for example)

**Comment by dmirgaleev** [comment]
@baitcode awesome, let's go!:)

**Comment by baitcode** [comment]
Can't start today. Will start working on Friday!

**Comment by dmirgaleev** [comment]
No worries, no strict timelines for this

**Comment by dmirgaleev** [comment]
Hey @baitcode! What's the status?

**Comment by baitcode** [comment]
@dmirgaleev  I've postponed it a bit. Been doing cairo quests on NodeGuardian to get more acquainted with the language. I'll submit PR soon. Pardon for silence. https://nodeguardians.io/character/baitcode

**Comment by baitcode** [comment]
@dmirgaleev created draft PR to this issue. I think I'll finish today or the next day.

**Comment by baitcode** [comment]
@dmirgaleev Could you, please, review?

**Comment by dmirgaleev** [comment]
Resolved in #85
