### ISSUE TITLE
[Book] Publish docs to GitHub Pages

### ISSUE THREAD

**Issue by dmirgaleev** [dipdup-io/stone-packaging#47]
Fork the repo. Use instructions to [build docs](https://github.com/dipdup-io/stone-packaging#usng-vocs-to-generate-documentation-localhost-site). Create a GitHub Actions workflow to build and publish documentation to GitHub Pages. Test if it works for your fork repo. 

- [ ] Provide link to the deployed website. 
- [ ] Provide all necessary instructions for https://github.com/dipdup-io/stone-packaging/settings/pages

**Comment by ShantelPeters** [comment]
Hi

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
Helllo, i am shantelpeters a frontend and blockchain developer with a strong background in languages like Java script, cario, solidity, css, react, typescript and html . please can i be assigned to this issue . i am ready to work.

### How I plan on tackling this issue
1. Fork the repo and follow the build instructions for the docs.
2. Create a GitHub Actions workflow to automatically build and publish docs to GitHub Pages.
3. Test the workflow on your fork, and verify if it deploys successfully.
4. Share the link to the deployed website.
5. Provide instructions for GitHub Pages setup in `stone-packaging/settings/pages`.

**Comment by akintewe** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stone-packaging-).

### My background and how it can be leveraged
I have a lot of expertise developing websites, specialising in JavaScript and CI/CD processes. I am a good fit for this project because of my experience dealing with automated deployment procedures, static site generators, and a variety of documentation systems over a number of years.  

### How I plan on tackling this issue
I would first set up a local setup to successfully produce the documentation, making sure I understand all dependencies and build stages, before publishing the documentation to GitHub Pages. To automate the procedure, I would then construct a GitHub Actions workflow file. This workflow would take care of the checkout, installation of dependencies, creation of documentation, and deployment to GitHub Pages. It would be triggered by pushes to the main branch and pull requests.
I would set up the repository settings to point to the appropriate branch and directory and enable GitHub Pages. I would confirm the process's effectiveness by testing it with a minor modification before documenting the whole procedure, which includes detailed instructions for configuring the GitHub Pages settings.

**Comment by dmirgaleev** [comment]
Hello @mexes20! Welcome aboard! Please don't hesitate to join our Telegram group [t.me/baking_bad_odhack](https://t.me/baking_bad_odhack) to ask questions and share your progress! Happy hacking!

**Comment by dmirgaleev** [comment]
Friendly heads up that you have till Sunday (October 6) to push final PR. @mexes20

**Comment by dmirgaleev** [comment]
Thank you! The integration with GitHub Pages still doesn't work correctly, probably because of Vocs or/and GitHub Pages limitations.
